<a href="https://colab.research.google.com/github/lavish537/python-practice/blob/main/python_classroom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY 1

In [ ]:
a,b,c=10,"hello","cse"

In [ ]:
type(b)
type(c)

str

In [ ]:
type(a)

int

In [ ]:
id(a)


10758024

In [ ]:
id(b)

134463576349296

In [ ]:
print(a)
print(b,c)

10
hello cse


In [ ]:
a,b,c=6,2,5
if(a>b):
  if(a>c):
    print(a," is large")
  else:
    print(c," is large")
else:
  if(b>c):
    print(b," is large")
  else:
    print(c," is large")


6  is large


In [ ]:
a,b,c,d,e=4,24,53,64,2
if(a>b and a>c and a>d and a>e):
  print(a," is largest")
elif(b>c and b>d and b>e):
  print(b," is largest")
elif( c>d and c>e):
  print(c," is largest")
elif(d>e):
  print(d," is largest")
else:
  print(e," is largest")

64  is largest


In [ ]:
i=1
while(i<11):
  print("5 x ",i," = ",i*5)
  i=i+1

5 x  1  =  5
5 x  2  =  10
5 x  3  =  15
5 x  4  =  20
5 x  5  =  25
5 x  6  =  30
5 x  7  =  35
5 x  8  =  40
5 x  9  =  45
5 x  10  =  50


In [ ]:
i=1
while(i<11):
  print("5 x ",i," = ",i*5)
  i=i+1
else:
  print("out of the loop")
  print("exit")

5 x  1  =  5
5 x  2  =  10
5 x  3  =  15
5 x  4  =  20
5 x  5  =  25
5 x  6  =  30
5 x  7  =  35
5 x  8  =  40
5 x  9  =  45
5 x  10  =  50
out of the loop
exit


In [ ]:
for i in range(11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(2,10,2):
  print(i)

2
4
6
8


In [ ]:
i=1
while(i<11):
  print("5 x ",i," = ",i*5)
  i=i+1

5 x  1  =  5
5 x  2  =  10
5 x  3  =  15
5 x  4  =  20
5 x  5  =  25
5 x  6  =  30
5 x  7  =  35
5 x  8  =  40
5 x  9  =  45
5 x  10  =  50


In [ ]:
for i in range(1,11):
  print("5 x ",i," = ",i*5)

5 x  1  =  5
5 x  2  =  10
5 x  3  =  15
5 x  4  =  20
5 x  5  =  25
5 x  6  =  30
5 x  7  =  35
5 x  8  =  40
5 x  9  =  45
5 x  10  =  50


In [ ]:
#area of rectangle
l=10
b=5
print(" area of rectangle is ",l*b)

 area of rectangle is  50


#day 2

In [ ]:
num=int(input("enter the no. : "))
for i in range(1,11):
  print(num," x ",i," = ",i*num)

enter the no. : 7
7  x  1  =  7
7  x  2  =  14
7  x  3  =  21
7  x  4  =  28
7  x  5  =  35
7  x  6  =  42
7  x  7  =  49
7  x  8  =  56
7  x  9  =  63
7  x  10  =  70


In [ ]:
l=float(input("enter length: "))
b=float(input("enter breadth: "))
print("perimeter of rectangle is ",2*(l+b))


enter length: 4
enter breadth: 3
perimeter of rectangle is  14.0


In [ ]:
r=float(input("enter radius of circle : "))
print("area of the circle is ", 3.14*r*r)

enter radius of circle : 10
area of the circle is  314.0


In [ ]:
#define function
def fun(fname):
  print("Hello user " + fname)
  print("Hello user " + fname)
  print("Hello user " + fname)
fun("hi")

Hello user hi
Hello user hi
Hello user hi


In [ ]:
def fun2(*k):
  print("Hello user " + k[0])
  print("Hello user " + k[1])
  print("Hello user " + k[2])
fun2("a","b","c")

Hello user a
Hello user b
Hello user c


In [ ]:
#default parameter
def fun3(fname= "Lavish"):
  print("Hello user " + fname)
  print("Hello user " + fname)
  print("Hello user " + fname)
fun3()
fun3("yo")

Hello user Lavish
Hello user Lavish
Hello user Lavish
Hello user yo
Hello user yo
Hello user yo


In [ ]:
def f1(x):
  return x*5
f1(10)

50

In [ ]:
def f2(child1,child3,child2):
  print("the value is "+ child3)
f2(child1='a',child2='b',child3='c')

the value is c


In [ ]:
def f3(**k):
  print("the value is "+ k['fname'])
f3(fname='a',mname='b',nname='c')

the value is a


In [ ]:
#calculator
def add(a,b):
  return a+b
def sub(a,b):
  return a-b
def multi(a,b):
  return a*b
def div(a,b):
  if(b==0):
    return "error"
  else:
    return a/b
def calc(var,a,b):
  if(var=="+"):
    print(sub(a,b))
  elif(var=="-"):
    print(sub(a,b))
  elif(var=="*"):
    print(multi(a,b))
  else:
    print(div(a,b))
f=float(input())
g=input()
h=float(input())
calc(g,f,h)

2
/
2
1.0


In [ ]:
#fibonacci series using recursion
def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
n = int(input("Enter the number of terms in the Fibonacci sequence: "))
print("Fibonacci sequence:")
for i in range(n):
    print(fibonacci(i), end=" ")

Enter the number of terms in the Fibonacci sequence: 5
Fibonacci sequence:
0 1 1 2 3 

In [ ]:
#factorial of a number
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)
n = int(input("Enter a number to calculate its factorial: "))
print("Factorial of", n, "is", factorial(n))

Enter a number to calculate its factorial: 5
Factorial of 5 is 120


In [ ]:
#to print all the prime within a given internval
def print_prime_numbers(n):
    print("Prime numbers up to", n, ":")
    for num in range(2, n + 1):
        is_prime = True
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            print(num, end=" ")
n = int(input("Enter a number to find all prime numbers up to it: "))
print_prime_numbers(n)

Enter a number to find all prime numbers up to it: 100
Prime numbers up to 100 :
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

In [ ]:
#add two binary no. by getting values from user
num1=input("Enter first binary number: ")
num2=input("Enter another binary number: ")
sum=bin(int(num1,2) + int(num2,2))
print("The sum of", num1, "and", num2, "in binary is:", sum)

Enter first binary number: 11
Enter another binary number: 11
The sum of 11 and 11 in binary is: 110


In [ ]:
#to take binary from user and print decimal
num3=input("enter binary number: ")
dec_num=int(num3,2)
print("The decimal equivalent of", num3, "is:", dec_num)

Day 4

In [ ]:
#add two binary no. specified in program
num1="1101"
num2="1011"
sum=bin(int(num1,2) + int(num2,2))
print("The sum of", num1, "and", num2, "in binary is:", sum[2:])

The sum of 1101 and 1011 in binary is: 11000


In [ ]:
#add two binary no. by getting values from user
num1=input("Enter first binary number: ")
num2=input("Enter another binary number: ")
sum=bin(int(num1,2) + int(num2,2))
print("The sum of", num1, "and", num2, "in binary is:", sum[2:])

Enter first binary number: 1101
Enter another binary number: 1011
The sum of 1101 and 1011 in binary is: 11000


In [ ]:
#to find power of a number
base=float(input("Enter base:"))
exponent=float(input("Enter exponent:"))
result=base**exponent
print(base,"to the power of",exponent,"is",result)

Enter base:2
Enter exponent:7
2.0 to the power of 7.0 is 128.0


In [ ]:
#while loop with break statement
while True:
  user_input=input("Type something (or 'exit' to stop):")
  if user_input=="exit":
    break
  print("Ymou typed:",user_input)

Type something (or 'exit' to stop):Lavish is the best
you typed: Lavish is the best
Type something (or 'exit' to stop):exit


In [ ]:
# to skip even numbers
for i in range(0,100):
  if i%2==0:
    continue
  print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [ ]:
# to print an array , sum of array and laregest element
numbers=[10,60,30,40,50,]
total=0
max=numbers[0]
for num in numbers:
  print(num)
  total+=num
  if num>max:
    max=num
print("Sum 0f array:",total)
print("largest element of array:",max)

10
60
30
40
50
Sum 0f array: 190
largest element of array: 60


In [ ]:
# Array using numpy
import numpy as np
numbers1=np.array([10,60,23,46])
print("Array 1:",numbers1)
numbers2=np.array([32,4,53,23])
print("Array 2:",numbers2)
sum_numbers=numbers1+numbers2
print("sum of arrays :",sum_numbers)
print("Max:",np.max(sum_numbers))
print("Min:",np.min(sum_numbers))
print("Sum:",np.sum(sum_numbers))
arr=np.arange(1,21)
print(arr)
reshaped=arr.reshape(10,2)
print("reshaped array:\n",reshaped)
result=arr*2
print("multiplied array:",result)
rand_arr=np.random.randint(1,100,size=5)
print("random array:",rand_arr)

Array 1: [10 60 23 46]
Array 2: [32  4 53 23]
sum of arrays : [42 64 76 69]
Max: 76
Min: 42
Sum: 251
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
reshaped array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
multiplied array: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
random array: [17 15 25 45 23]


Day 5

In [ ]:
num=[]
n=int(input("enter no of elements:"))
even_count=0
odd_count=0
for i in  range(0,n):
  num.append(int(input("enter element:")))
for i in range (n):
  if(num[i]%2==0):
    even_count+=1
  else:
    odd_count+=1
print("Odd:",odd_count)
print("Even:",even_count)
print("Revese of array =",num[::-1])

enter no of elements:5
enter element:2
enter element:3
enter element:4
enter element:5
enter element:6
Odd: 2
Even: 3
Revese of array = [6, 5, 4, 3, 2]


In [ ]:
array1=[]
n=int(input("enter no of elements:"))
for i in  range(0,n):
  array1.append(i)
print(array1)

enter no of elements:100
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [ ]:
import numpy as np
numbers1=np.array([10,60,23,46])
print("Array 1:",numbers1)
numbers2=np.array([32,4,53,23])
print("Array 2:",numbers2)
sum_numbers=numbers1+numbers2
print("sum of arrays :",sum_numbers)

Array 1: [10 60 23 46]
Array 2: [32  4 53 23]
sum of arrays : [42 64 76 69]


In [ ]:
item=int(input("enter the element to be searched:"))
index=-1
for i in range(n):
  if array1[i]==item:
    index=i-1
    break
if index==-1:
  print("element not found")
else:
  print("element found at index:",index)


enter the element to be searched:23
element found at index: 22


Day 6


In [ ]:
arr1=[]
sum1=0
even=0
odd=0
n=int(input("Enter no of elements to be entered:"))
for i in range(n):
    x=int(input("Enter element:"))
    arr1.append(x)
    sum1+=x
print(arr1)
print("sum=",sum1)
print("max=",max(arr1))
for i in arr1:
  if i%2==0:
    even+=1
  else:
    odd+=1
triple=[]
for i in range(len(arr1)):
    triple.append(arr1[i]*3)
print("triple=",triple)
print("odd=",odd)
print("even=",even)
print("array=",arr1)
reverse=[]
for i in range(len(arr1)):
    reverse.append(arr1[len(arr1)-1-i])
print("reverse=",reverse)

50
0
5
[ 30  60  90 120 150]
[10 20 30 40 50]
[50 40 30 20 10]


In [ ]:
arr1=[]
n=int(input("Enter no of elements to be entered:"))
for i in range(n):
    x=int(input("Enter element:"))
    arr1.append(x)
while True:
    sum1=0
    even=0
    odd=0
    print("""\nMenu:-
1.Print array
2.Print sum
3.Print max
4.Print Triple
5.Print reverse
6.Print Odd and Even
7.Exit\n
""")
    choice=input("Enter choice:")
    for i in range(n):
        sum1+=x
    if choice=="1":
        print(arr1)
    elif choice=="2":
        print("sum =",sum1)
    elif choice=="3":
        print("max =",max(arr1))
    elif choice=="4":
        triple=[]
        for i in range(n):
            triple.append(arr1[i]*3)
        print("triple =",triple)
    elif choice=="5":
        print("array =",arr1)
        reverse=[]
        for i in range(n):
            reverse.append(arr1[n-1-i])
        print("reverse =",reverse)
    elif choice=="6":
        for i in arr1:
            if i%2==0:
                even+=1
            else:
                odd+=1
        print("odd =",odd)
        print("even =",even)
    elif choice=="7":
        break;
    else:
        print("\nenter a valid choice\n")
        continue

Day 7

In [ ]:
from functools import reduce
# Lambda function
"""small function (one expression) with no name(anonymous)
compact in nature(1 line)
any no. of arguments can be given(Arbitrary arguments)
Syntax:-
lambda arguments : expression"""
l=lambda x:x+10
print(l(5))
multiply=lambda a,b:a*b
print(multiply(5,6))
def myfunc(n):
  return lambda a:a*n
mydoubler=myfunc(2)
print(mydoubler(11))
mytripler=myfunc(3)
print(mytripler(11))
add=lambda x,y,z:x+y+z
print(add(1,2,3))
nums=[1,2,3,4,5,6,7,8,9,0]
even=list(filter(lambda x:x%2==0,nums))    # filter data
print(even)
double=list(map(lambda x:x*2,nums))        # map one by one access data
print(double)
square=list(map(lambda x:x**2,nums))
print(square)
s1="hello world"
s2=lambda func:func.upper()
print(s2(s1))
n=lambda x:"positive" if x>0 else "negative" if x<0 else "zero"
print(n(5))
a=[1,2,3,4]
b=reduce(lambda x,y:x*y,a)                 # reduce() function from functools
print(b)
li=[lambda arg=x:arg*10 for x in range(1,5)]
for i in li:
  print(i())
calc=lambda x,y:(x+y,x*y)
res=calc(3,4)
print(res)

15
30
22
33
6
[2, 4, 6, 8, 0]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 0]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 0]
HELLO WORLD
positive
24
10
20
30
40
(7, 12)


Day 8

In [ ]:
txt="         hEllo WorLd           "
txt2="!!!!"
print(txt.capitalize())
print(txt.upper())
print(txt.lower())
print(txt.title())
print(txt.strip())
print(txt.lstrip())
print(txt.rstrip())
print(txt.startswith('h'))
print(txt.split())
print(txt.islower())
print(txt.isupper())
print(txt.isalpha())
print(txt.isnumeric())
print(txt.isdigit())
print(txt.count('o'))
print(txt.replace(" ",'_'))
print(txt.find('r'))
print(txt.index('r'))
print(txt.swapcase())
print(txt.isalnum())
print(txt+txt2)
print(txt.join(txt2))

         hello world           
         HELLO WORLD           
         hello world           
         Hello World           
hEllo WorLd
hEllo WorLd           
         hEllo WorLd
False
['hEllo', 'WorLd']
False
False
False
False
False
2
_________hEllo_WorLd___________
17
17
         HeLLO wORlD           
False
         hEllo WorLd           !!!!
!         hEllo WorLd           !         hEllo WorLd           !         hEllo WorLd           !


Day 9


In [ ]:
txt=input("Enter a sting")
print(txt[::-1])
print(txt.capitalize())
print(txt.upper())
print(txt.lower())
print(txt.title())
print(txt.strip())
print(txt.lstrip())
print(txt.rstrip())
print(txt.startswith('h'))
print(txt.split())
print(txt.islower())
print(txt.isupper())
print(txt.isalpha())
print(txt.isnumeric())
print(txt.isdigit())
print(txt.count('o'))
print(txt.replace(" ",'_'))
print(txt.swapcase())
print(txt.isalnum())
txt2="!!!!"
print(txt+txt2)
print(txt.join(txt2))

Enter a stinghello world!
!dlrow olleh
Hello world!
HELLO WORLD!
hello world!
Hello World!
hello world!
hello world!
hello world!
True
['hello', 'world!']
True
False
False
False
False
2
hello_world!
8
8
HELLO WORLD!
False
hello world!!!!!
!hello world!!hello world!!hello world!!


In [ ]:
# reverse of a no
a=int(input("enter any no."))
reverse=0;
while (a>=0):
  reverse=reverse*10+a%10
  a=a//10
  if(a==0):
    break
print("reverse =",reverse)


enter any no.1230
reverse= 321


In [ ]:
# reverse
a=input("enter any no.")
reverse=a[::-1]
print(reverse)

enter any no.1230
0321


In [ ]:
# to calculate SI and CI
p=float(input("enter principal amount:"))
r=float(input("enter rate:"))/100
t=float(input("enter time:"))
SI=p*r*t
n=float(input("enter no of times interest is compounded per time period:"))
Ci=p*(1+r/n)**n*t
print("Simple Interest:",SI)
print("Compound Interest:",Ci)

enter principal amount:10000
enter rate:5
enter time:2
enter no of times interest is compounded per time period:12
Simple Interest: 1000.0
Compound Interest: 21023.23795763466


In [ ]:
# celcius to fahrenheit
c=float(input("enter temp in celcius:"))
f=c*9/5+32
print("temp in fahrenheit:",f)

enter temp in celcius100
temp in fahrenheit: 212.0


In [ ]:
# to find sum of digit of a number
a=int(input("enter any no."))
sum=0
while (a>0):
  sum+=a%10
  a=a//10
print("sum =",sum)

enter any no.123
sum = 6


In [ ]:
# count alphabets digits and symbols
a=input("Enter any string")
alphabets=0
digits=0
symbols=0
for char in a:
        if char.isalpha():
            alphabets += 1
        elif char.isdigit():
            digits += 1
        else:
            symbols += 1
print("Alphabets:", alphabets)
print("Digits:", digits)
print("Symbols:", symbols)



Enter any stringhello @123
Alphabets: 5
Digits: 3
Symbols: 2


In [ ]:
# palindrome
a=input("enter any string")
if(a==a[::-1]):
  print("palindrome")
else:
  print("not palindrome")

Day 10

In [ ]:
# to search an element in an array
a=[]
n=int(input("enter no of elements:"))
for i in range(n):
  a.append(int(input("enter element:")))
x=int(input("enter element to be searched:"))
for i in a:
  if(i==x):
    print("element found at index:",a.index(i))
    break
else:
  print("element not found")

enter no of elements:5
enter element:1
enter element:2
enter element:3
enter element:4
enter element:5
enter element to be searched:2
element found at index: 1


In [ ]:
# generate a game to guess a no.
import random
n=random.randint(0,10)
attempts=0
print(n)
while True:
  z=int(input("Enter your guess(between 0-10):"))
  if(z>10 or z<0):
    print("Guess no. between 0-10 only")
    continue
  if(z==n):
    print("Congratulations You guessed it right in",attempts+1,"attempts")
    break
  else:
    print("Try again")
    attempts+=1
    if(z<n):
      print("too low")
    elif(z>n):
      print("too high")
    if(attempts==4):
        print("You Lost")
        break
    print("only",4-attempts,"left")

6
Enter your guess(between 0-10):2
Try again
too low
only 3 left
Enter your guess(between 0-10):1
Try again
too low
only 2 left
Enter your guess(between 0-10):3
Enter your guess(between 0-10):4
Try again
too low
only 1 left
Try again
too low
only 0 left
You Lost


In [ ]:
#generate a random array of size 10
import numpy as np
import random
arr = np.array([random.randint(1, 100) for i in range(10)])
print("Original array:\n", arr)
reshaped=arr.reshape(2,5)
print("reshaped array:\n",reshaped)

Original array:
 [70 42 45 90  7 87 64 64 57 22]
reshaped array:
 [[70 42 45 90  7]
 [87 64 64 57 22]]


DAY 11

In [14]:
#to find sum of list elements
l1=[1,2,3,5,3,5]
print("list:",l1)
sum=0
for i in l1:
  sum+=i
print("sum:",sum)
#to find largest , second largest and smallest element of list
max=l1[0]
min=l1[0]
max2=l1[0]
for i in range(len(l1)):
  if l1[i]>max:
    max=l1[i]
  if l1[i]<min:
    min=l1[i]
for i in range(len(l1)):
  if l1[i]>max2 and l1[i]!=max:
    max2=l1[i]
print("Largest:",max)
print("Second Largest:",max2)
print("Smallest:",min)
#to print reverse of list
print("reverse:",l1[::-1])
#to find occurances of a number in a list
target=int(input("enter target:"))
count=0
for i in l1:
  if i==target:
    count+=1
print("occurances:",count)
if(count==0):
  print("Element not in list")
#to find even and odd no, in list
even=[]
odd=[]
for i in l1:
  if (i%2==0):
    even.append(i)
  else:
    odd.append(i)
print("no. of even no.:",len(even))
print("even:",even)
print("no. of odd no.:",len(odd))
print("odd:",odd)
#to find occurances of all number in a list
occurances={}
for i in l1:
  if i in occurances:
    occurances[i]+=1
  else:
    occurances[i]=1
print("occurances:",occurances)
for i in occurances:
  if(occurances[i]<=1):
    print(i,"has occured",occurances[i],"time")
  else:
    print(i,"has occured",occurances[i],"times")
#to find square of each list elements
squared=[]
for i in l1:
  squared.append(i**2)
print("Square of each element:",squared)
#to sort list in ascending and descending order
print("Ascending:",sorted(l1))
print("Descending:",sorted(l1,reverse=True))
#merge 2 lists
l2=[3,1,3,4,2,4,5,6]
l3=l1+l2
print("Merge:",l3)
l4=[]
n=int(input("Enter no. of elements"))
for i in range(n):
  x=int(input("Enter element"))
  l4.append(x)
print("User input list:",l4)
#
l5=[10,5,6,20,4]
l5=sorted(l5)
max=l5[-1]*l5[-2]*l5[-3]
print("Maximum product:",max)

list: [1, 2, 3, 5, 3, 5]
sum: 19
Largest: 5
Second Largest: 3
Smallest: 1
reverse: [5, 3, 5, 3, 2, 1]
enter target:5
occurances: 2
no. of even no.: 1
even: [2]
no. of odd no.: 5
odd: [1, 3, 5, 3, 5]
occurances: {1: 1, 2: 1, 3: 2, 5: 2}
1 has occured 1 time
2 has occured 1 time
3 has occured 2 times
5 has occured 2 times
Square of each element: [1, 4, 9, 25, 9, 25]
Ascending: [1, 2, 3, 3, 5, 5]
Descending: [5, 5, 3, 3, 2, 1]
Merge: [1, 2, 3, 5, 3, 5, 3, 1, 3, 4, 2, 4, 5, 6]
Enter no. of elements5
Enter element1
Enter element2
Enter element3
Enter element4
Enter element5
User input list: [1, 2, 3, 4, 5]
Maximum product: 1200
